import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { mobileApi } from '../services/mobileApi';

const STORAGE_KEY = 'rankcine_language';

export const TRANSLATIONS = {
  EN: {
    choose_language: 'Choose your language',
    tab_discover: 'DISCOVER',
    tab_ratings: 'RATINGS',
    tab_profile: 'PROFILE',
    search_placeholder: 'Search titles, formats, or creators...',
    syncing_stream: 'SYNCING ARCHITECTURAL STREAM...',
    no_content_matched: 'NO CONTENT MATCHED',
    no_content_sub: 'No assets found matching your fuzzy search query.',
    ai_pre_score: 'AI PRE-SCORE',
    rate: 'RATE',
    consensus_draw: '0.5 CONSENSUS DRAW',
    filter_media_types: 'FILTER MEDIA TYPES',
    apply_filters: 'APPLY FILTERS',
    sort_discovery_feed: 'SORT DISCOVERY FEED',
    system_notifications: 'SYSTEM NOTIFICATIONS',
    reward_won: 'REWARD WON',
    view_all_rewards: 'VIEW ALL REWARDS',
    all_caught_up: 'All Caught Up',
    no_notifications_sub: 'New consensus reward voucher draws will appear here.',
    account_suspended: 'ACCOUNT SUSPENDED',
    email_support_team: 'EMAIL SUPPORT TEAM',
    log_out: 'LOG OUT',
    rate_content: 'RATE CONTENT',
    verifying_audit: 'VERIFYING PREVIOUS AUDIT STATUS...',
    parameters: 'PARAMETERS',
    ai_formatting_on: 'AI FORMATTING STATUS: ON',
    record_audio_video: 'RECORD AUDIO/VIDEO',
    type_input_placeholder: 'Type text input here or attach audio/video recording...',
    processing_ai: 'PROCESSING GEMINI AI...',
    submit_review: 'SUBMIT REVIEW',
    report_content: 'REPORT CONTENT',
    submission_analytics: 'SUBMISSION ANALYTICS',
    rating: 'RATING',
    quality: 'QUALITY',
    ai_synthesized_review_output: 'AI SYNTHESIZED REVIEW OUTPUT',
    return_to_feed: 'RETURN TO FEED ►',
    share_audit: 'SHARE AUDIT',
    total_reviewed: 'TOTAL ITEMS REVIEWED',
    account_settings: 'ACCOUNT SETTINGS',
    my_reviewed_items: 'My Reviewed Items',
    my_rewards: 'My Rewards',
    edit_profile: 'Edit Profile',
    help_support: 'Help & Support',
    audit_history: 'AUDIT HISTORY',
    filter: 'Filter',
    syncing_review_archive: 'SYNCING REVIEW ARCHIVE...',
    evaluated_on: 'EVALUATED ON',
    sentiment: 'SENTIMENT:',
    reward_unlocked: 'REWARD UNLOCKED',
    view_consensus: 'View Consensus →',
    no_evaluations_found: 'No evaluations found in your archive.',
    rate_media_sub: 'Rate media on the discovery feed to build your evaluation ledger.',
    filter_reviews: 'FILTER REVIEWS',
    reset: 'Reset',
    content_type: 'CONTENT TYPE',
    reward_status: 'REWARD STATUS',
    all_types: 'All Types',
    all_reviews: 'All Reviews',
    reward_vouchers_unlocked: 'Reward Vouchers Unlocked Only',
    no_rewards: 'No Rewards',
    unlocked_vouchers: 'UNLOCKED VOUCHERS',
    syncing_reward_ledger: 'SYNCING REWARD LEDGER...',
    won: 'WON:',
    sponsor: 'SPONSOR:',
    redeemed: 'REDEEMED',
    unclaimed: 'UNCLAIMED',
    no_won_vouchers: 'No won vouchers in your ledger.',
    rate_content_sub: 'Rate content and match the 0.5 consensus mode peak to win lucky draw sponsor rewards.',
    reward_voucher: 'REWARD VOUCHER',
    issued_by: 'Issued by',
    voucher_redemption_code: 'VOUCHER REDEMPTION CODE',
    present_code_desc: 'Present or apply this code on the sponsor website to redeem your reward.',
    mark_as_redeemed: 'MARK AS REDEEMED',
    voucher_already_redeemed: 'VOUCHER ALREADY REDEEMED',
    voucher_status: 'VOUCHER STATUS',
    all_vouchers: 'All Vouchers',
    unclaimed_only: 'Unclaimed Only',
    redeemed_only: 'Redeemed Only',
    consensus_rewards: 'CONSENSUS & REWARDS',
    consensus_tab: '0.5 CONSENSUS',
    lucky_draw_tab: 'LUCKY DRAW REWARDS',
    calculating_bins: 'CALCULATING 0.5 CONSENSUS BINS...',
    current_consensus_peak: 'CURRENT CONSENSUS MODE PEAK',
    in_draw_pool: 'IN DRAW POOL',
    crowd_rating_distribution: 'CROWD RATING DISTRIBUTION (0.0 – 10.0)',
    consensus_peak: 'Consensus Peak',
    your_rating: 'Your Rating',
    top_consensus_rankings: 'TOP CONSENSUS RANKINGS',
    rating_bucket: 'Rating Bucket',
    evaluators: 'Evaluators',
    votes: 'votes',
    winners_draw: 'WINNERS',
    reward_budget: 'REWARD BUDGET:',
    status: 'STATUS:',
    target: 'TARGET:',
    full_name: 'FULL NAME',
    phone_number: 'PHONE NUMBER',
    verified: 'VERIFIED',
    email: 'EMAIL',
    date_of_birth: 'DATE OF BIRTH',
    month: 'MONTH',
    day: 'DAY',
    year: 'YEAR',
    country: 'COUNTRY',
    state_province: 'STATE / PROVINCE',
    city: 'CITY',
    street_address: 'STREET ADDRESS',
    address_line_2: 'ADDRESS LINE 2 (OPTIONAL)',
    languages_known: 'LANGUAGES KNOWN',
    select_more_language: 'Select More Language',
    gender_optional: 'GENDER (OPTIONAL)',
    male: 'MALE',
    female: 'FEMALE',
    other: 'OTHER',
    save_profile: 'SAVE PROFILE',
    saving: 'SAVING...',
    select_languages_modal: 'SELECT LANGUAGES KNOWN',
    changes_not_saved_title: 'CHANGES MADE WILL NOT BE SAVED',
    changes_not_saved_sub: 'DO YOU WANT TO DISCARD CHANGES AND EXIT?',
    discard: 'DISCARD',
    keep_editing: 'KEEP EDITING',
    consumer_auth: 'CONSUMER AUTHENTICATION',
    email_or_phone: 'EMAIL OR PHONE NUMBER',
    generate_otp: 'GENERATE\nOTP',
    otp_label: 'OTP VERIFICATION',
    accept_terms_prefix: 'I accept the ',
    terms_link: 'Terms of Service & Privacy Policy',
    login_button: 'LOG IN',
    or_social_login: 'OR SOCIAL LOGIN',
    new_user_register: 'NEW USER? REGISTER PROFILE HERE',
    faq_section_title: 'FREQUENTLY ASKED QUESTIONS',
    contact_support_team: 'CONTACT SUPPORT TEAM',
    select_category: 'SELECT ISSUE CATEGORY',
    subject: 'SUBJECT',
    subject_placeholder: 'Brief description of issue...',
    detailed_message: 'DETAILED MESSAGE',
    message_placeholder: 'Describe what happened, including asset IDs or rewards...',
    submit_ticket: 'SUBMIT SUPPORT TICKET',
    skip: 'SKIP',
    get_started: 'GET STARTED',
    next: 'NEXT',
    onboarding_title_1: 'Unlock Elite Rewards',
    onboarding_desc_1: 'Join a community of top-tier reviewers and earn exclusive access to premium architectural assets. Your precision pays off.',
    onboarding_title_2: 'Your Reward Portfolio',
    onboarding_desc_2: 'Track your progress and archived earnings. A chronological ledger of your accuracy milestones and exclusive rewards.',
    onboarding_title_3: 'Rate for Rewards',
    onboarding_desc_3: 'Every accurate rating brings you closer to unlocking new system tiers and sponsor-backed rewards. Quality feedback is your currency.',
    onboarding_title_4: 'Elite Percentile Rank',
    onboarding_desc_4: 'Reach the top 5% of community accuracy to unlock the most prestigious project rewards. Our sponsors value your architectural precision.',
    onboarding_title_5: 'Start Your Reward Journey',
    onboarding_desc_5: 'Your workspace is synchronized. High-accuracy reviews are the key to building your professional asset library. Begin your first project.',
    create_consumer_profile: 'CREATE CONSUMER PROFILE',
    username_handle: 'USERNAME (@HANDLE)',
    select_country: 'Select Country',
    select_state: 'Select State',
    complete_profile_button: 'COMPLETE PROFILE ►',
    clear: 'CLEAR',
    report_media_headline: 'Report Media Asset',
    report_media_subtext: 'Please select the reason that best describes your concern regarding this content. Our moderation team will audit it.',
    reason_age_inappropriate: 'AGE INAPPROPRIATE',
    reason_unrelated_content: 'UNRELATED CONTENT',
    reason_false_ad: 'FALSE ADVERTISEMENT / CONTENT',
    reason_other: 'OTHER',
    submit_report: 'SUBMIT REPORT',
    cancel: 'CANCEL',
    terms_privacy_title: 'TERMS & PRIVACY POLICY',
    privacy_policy_tab: 'PRIVACY POLICY (DPDP 2023)',
    terms_of_service_tab: 'TERMS OF SERVICE',
    legal_compliance_header: 'COMPLIANCE: INDIA DIGITAL PERSONAL DATA PROTECTION ACT 2023 • IT ACT 2000',
    understand_accept_policies: 'I UNDERSTAND & ACCEPT POLICIES',
    media_recording_studio: 'MEDIA RECORDING STUDIO',
    audio_review: 'AUDIO REVIEW',
    video_review: 'VIDEO REVIEW',
    video_preview_ready: 'VIDEO PREVIEW READY',
    camera_viewfinder_active: 'CAMERA VIEWFINDER ACTIVE',
    audio_preview_ready: 'AUDIO PREVIEW READY',
    microphone_active: 'MICROPHONE ACTIVE',
    re_record: 'RE-RECORD',
    attach_to_review: 'ATTACH TO REVIEW ✓',
    TRAILER: 'TRAILER',
    POSTER: 'POSTER',
    SONG: 'SONG',
    PODCAST: 'PODCAST',
    ARTICLE: 'ARTICLE',
    TEXT: 'TEXT',
    AUDIO: 'AUDIO',
    VIDEO: 'VIDEO',
    Acting: 'Acting',
    Visuals: 'Visuals',
    Pacing: 'Pacing',
    Originality: 'Originality',
    Audio: 'Audio',
    Direction: 'Direction',
    Cinematography: 'Cinematography'
  },
  HI: {
    choose_language: 'अपनी भाषा चुनें',
    tab_discover: 'खोजें',
    tab_ratings: 'रेटिंग्स',
    tab_profile: 'प्रोफ़ाइल',
    search_placeholder: 'शीर्षक, प्रारूप या निर्माता खोजें...',
    syncing_stream: 'स्ट्रीम लोड हो रही है...',
    no_content_matched: 'कोई परिणाम नहीं मिला',
    no_content_sub: 'आपकी खोज से मेल खाने वाला कोई कंटेंट नहीं मिला।',
    ai_pre_score: 'एआई स्कोर',
    rate: 'रेट करें',
    consensus_draw: '0.5 आम सहमति ड्रा',
    filter_media_types: 'मीडिया प्रकार फ़िल्टर करें',
    apply_filters: 'फ़िल्टर लागू करें',
    sort_discovery_feed: 'क्रमबद्ध करें',
    system_notifications: 'सिस्टम सूचनाएं',
    reward_won: 'इनाम जीता',
    view_all_rewards: 'सभी इनाम देखें',
    all_caught_up: 'सब अपडेट है',
    no_notifications_sub: 'नए इनाम वाउचर ड्रा यहाँ दिखाई देंगे।',
    account_suspended: 'खाता निलंबित',
    email_support_team: 'सपोर्ट टीम को ईमेल करें',
    log_out: 'लॉग आउट',
    rate_content: 'रेटिंग दें',
    verifying_audit: 'ऑडिट स्थिति जांची जा रही है...',
    parameters: 'पैरामीटर्स',
    ai_formatting_on: 'एआई स्थिति: सक्रिय',
    record_audio_video: 'ऑडियो/वीडियो रिकॉर्ड करें',
    type_input_placeholder: 'यहाँ अपनी समीक्षा लिखें या रिकॉर्डिंग जोड़ें...',
    processing_ai: 'एआई विश्लेषण जारी...',
    submit_review: 'समीक्षा जमा करें',
    report_content: 'रिपोर्ट करें',
    submission_analytics: 'सबमिशन विश्लेषण',
    rating: 'रेटिंग',
    quality: 'गुणवत्ता',
    ai_synthesized_review_output: 'एआई सारांश आउटपुट',
    return_to_feed: 'फ़ीड पर वापस जाएं ►',
    share_audit: 'ऑडिट साझा करें',
    total_reviewed: 'कुल समीक्षित सामग्री',
    account_settings: 'खाता सेटिंग्स',
    my_reviewed_items: 'मेरी समीक्षित सामग्री',
    my_rewards: 'मेरे इनाम',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    help_support: 'सहायता और समर्थन',
    audit_history: 'ऑडिट इतिहास',
    filter: 'फ़िल्टर',
    syncing_review_archive: 'समीक्षा संग्रह लोड हो रहा है...',
    evaluated_on: 'समीक्षा दिनांक',
    sentiment: 'सेंटीमेंट:',
    reward_unlocked: 'इनाम अनलॉक हुआ',
    view_consensus: 'आम सहमति देखें →',
    no_evaluations_found: 'आपके संग्रह में कोई समीक्षा नहीं मिली।',
    rate_media_sub: 'समीक्षा खाता बनाने के लिए फ़ीड पर सामग्री को रेट करें।',
    filter_reviews: 'समीक्षाएं फ़िल्टर करें',
    reset: 'रीसेट',
    content_type: 'सामग्री प्रकार',
    reward_status: 'इनाम स्थिति',
    all_types: 'सभी प्रकार',
    all_reviews: 'सभी समीक्षाएं',
    reward_vouchers_unlocked: 'केवल अनलॉक इनाम',
    no_rewards: 'कोई इनाम नहीं',
    unlocked_vouchers: 'अनलॉक किए गए वाउचर',
    syncing_reward_ledger: 'इनाम लेज़र लोड हो रहा है...',
    won: 'जीता:',
    sponsor: 'प्रायोजक:',
    redeemed: 'रिडीम किया गया',
    unclaimed: 'दावा नहीं किया',
    no_won_vouchers: 'आपके लेज़र में कोई जीता हुआ वाउचर नहीं है।',
    rate_content_sub: 'इनाम जीतने के लिए सामग्री को रेट करें और 0.5 आम सहमति मोड से मेल खाएं।',
    reward_voucher: 'इनाम वाउचर',
    issued_by: 'जारीकर्ता:',
    voucher_redemption_code: 'वाउचर रिडेम्पशन कोड',
    present_code_desc: 'अपने इनाम को रिडीम करने के लिए प्रायोजक वेबसाइट पर यह कोड लागू करें।',
    mark_as_redeemed: 'रिडीम के रूप में चिह्नित करें',
    voucher_already_redeemed: 'वाउचर पहले ही रिडीम किया जा चुका है',
    voucher_status: 'वाउचर स्थिति',
    all_vouchers: 'सभी वाउचर',
    unclaimed_only: 'केवल बिना दावे वाले',
    redeemed_only: 'केवल रिडीम किए गए',
    consensus_rewards: 'आम सहमति और इनाम',
    consensus_tab: '0.5 आम सहमति',
    lucky_draw_tab: 'लकी ड्रा इनाम',
    calculating_bins: '0.5 आम सहमति बिन की गणना हो रही है...',
    current_consensus_peak: 'वर्तमान आम सहमति मोड पीक',
    in_draw_pool: 'ड्रा पूल में शामिल',
    crowd_rating_distribution: 'सामूहिक रेटिंग वितरण (0.0 – 10.0)',
    consensus_peak: 'आम सहमति पीक',
    your_rating: 'आपकी रेटिंग',
    top_consensus_rankings: 'शीर्ष आम सहमति रैंकिंग',
    rating_bucket: 'रेटिंग बकेट',
    evaluators: 'समीक्षक',
    votes: 'वोट',
    winners_draw: 'विजेता',
    reward_budget: 'इनाम बजट:',
    status: 'स्थिति:',
    target: 'लक्ष्य:',
    full_name: 'पूरा नाम',
    phone_number: 'फ़ोन नंबर',
    verified: 'सत्यापित',
    email: 'ईमेल',
    date_of_birth: 'जन्म तिथि',
    month: 'माह',
    day: 'दिन',
    year: 'वर्ष',
    country: 'देश',
    state_province: 'राज्य / प्रांत',
    city: 'शहर',
    street_address: 'गली का पता',
    address_line_2: 'पता पंक्ति 2 (वैकल्पिक)',
    languages_known: 'ज्ञात भाषाएँ',
    select_more_language: 'और भाषा चुनें',
    gender_optional: 'लिंग (वैकल्पिक)',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    save_profile: 'प्रोफ़ाइल सहेजें',
    saving: 'सहेजा जा रहा है...',
    select_languages_modal: 'ज्ञात भाषाएँ चुनें',
    changes_not_saved_title: 'किए गए बदलाव सहेजे नहीं जाएंगे',
    changes_not_saved_sub: 'क्या आप बदलाव छोड़ना और बाहर निकलना चाहते हैं?',
    discard: 'छोड़ें',
    keep_editing: 'संपादन जारी रखें',
    consumer_auth: 'उपभोक्ता प्रमाणीकरण',
    email_or_phone: 'ईमेल या फ़ोन नंबर',
    generate_otp: 'ओटीपी\nप्राप्त करें',
    otp_label: 'ओटीपी सत्यापन',
    accept_terms_prefix: 'मैं स्वीकार करता हूँ ',
    terms_link: 'नियम और गोपनीयता नीति',
    login_button: 'लॉग इन करें',
    or_social_login: 'या सोशल लॉगिन',
    new_user_register: 'नए उपयोगकर्ता? यहाँ रजिस्टर करें',
    faq_section_title: 'अक्सर पूछे जाने वाले प्रश्न',
    contact_support_team: 'सपोर्ट टीम से संपर्क करें',
    select_category: 'मुद्दे की श्रेणी चुनें',
    subject: 'विषय',
    subject_placeholder: 'मुद्दे का संक्षिप्त विवरण...',
    detailed_message: 'विस्तृत संदेश',
    message_placeholder: 'विस्तार से बताएं कि क्या हुआ...',
    submit_ticket: 'सपोर्ट टिकट जमा करें',
    skip: 'छोड़ें',
    get_started: 'शुरू करें',
    next: 'आगे',
    onboarding_title_1: 'विशिष्ट इनाम अनलॉक करें',
    onboarding_desc_1: 'शीर्ष समीक्षकों के समुदाय में शामिल हों और विशेष सुविधाओं तक पहुंच प्राप्त करें।',
    onboarding_title_2: 'आपका इनाम पोर्टफोलियो',
    onboarding_desc_2: 'अपनी प्रगति और अर्जित इनामों को ट्रैक करें।',
    onboarding_title_3: 'इनाम के लिए रेटिंग दें',
    onboarding_desc_3: 'प्रत्येक सटीक रेटिंग आपको नए प्रायोजक इनामों के करीब लाती है।',
    onboarding_title_4: 'शीर्ष प्रतिशत रैंक',
    onboarding_desc_4: 'सर्वोत्तम इनामों को अनलॉक करने के लिए शीर्ष 5% सटीकता तक पहुँचें।',
    onboarding_title_5: 'अपनी यात्रा शुरू करें',
    onboarding_desc_5: 'सटीक समीक्षाएं आपकी सफलता की कुंजी हैं। अपना पहला प्रोजेक्ट शुरू करें।',
    create_consumer_profile: 'उपभोक्ता प्रोफ़ाइल बनाएं',
    username_handle: 'उपयोगकर्ता नाम (@हैंडल)',
    select_country: 'देश चुनें',
    select_state: 'राज्य चुनें',
    complete_profile_button: 'प्रोफ़ाइल पूर्ण करें ►',
    clear: 'साफ़ करें',
    report_media_headline: 'मीडिया सामग्री की रिपोर्ट करें',
    report_media_subtext: 'कृपया वह कारण चुनें जो इस सामग्री के संबंध में आपकी चिंता का सबसे अच्छा वर्णन करता है।',
    reason_age_inappropriate: 'आयु अनुचित',
    reason_unrelated_content: 'असंबंधित सामग्री',
    reason_false_ad: 'झूठा विज्ञापन / सामग्री',
    reason_other: 'अन्य',
    submit_report: 'रिपोर्ट जमा करें',
    cancel: 'रद्द करें',
    terms_privacy_title: 'नियम और गोपनीयता नीति',
    privacy_policy_tab: 'गोपनीयता नीति (DPDP 2023)',
    terms_of_service_tab: 'सेवा की शर्तें',
    legal_compliance_header: 'अनुपालन: भारत डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम 2023 • आईटी अधिनियम 2000',
    understand_accept_policies: 'मैं नीतियां समझता हूँ और स्वीकार करता हूँ',
    media_recording_studio: 'मीडिया रिकॉर्डिंग स्टूडियो',
    audio_review: 'ऑडियो समीक्षा',
    video_review: 'वीडियो समीक्षा',
    video_preview_ready: 'वीडियो पूर्वावलोकन तैयार',
    camera_viewfinder_active: 'कैमरा दृश्यदर्शी सक्रिय',
    audio_preview_ready: 'ऑडियो पूर्वावलोकन तैयार',
    microphone_active: 'माइक्रोफ़ोन सक्रिय',
    re_record: 'पुनः रिकॉर्ड करें',
    attach_to_review: 'समीक्षा में संलग्न करें ✓',
    TRAILER: 'ट्रेलर',
    POSTER: 'पोस्टर',
    SONG: 'गाना',
    PODCAST: 'पॉडकास्ट',
    ARTICLE: 'लेख',
    TEXT: 'टेक्स्ट',
    AUDIO: 'ऑडियो',
    VIDEO: 'वीडियो',
    Acting: 'अभिनय',
    Visuals: 'दृश्य',
    Pacing: 'गति',
    Originality: 'मौलिकता',
    Audio: 'ऑडियो',
    Direction: 'निर्देशन',
    Cinematography: 'छायांकन'
  },
  TE: {
    choose_language: 'మీ భాషను ఎంచుకోండి',
    tab_discover: 'కనుగొనండి',
    tab_ratings: 'రేటింగ్‌లు',
    tab_profile: 'ప్రొఫైల్',
    search_placeholder: 'శీర్షికలు లేదా రూపకర్తలను శోధించండి...',
    syncing_stream: 'స్ట్రీమ్ లోడ్ అవుతోంది...',
    no_content_matched: 'కంటెంట్ కనుగొనబడలేదు',
    no_content_sub: 'మీ శోధనకు సరిపోలే కంటెంట్ కనుగొనబడలేదు.',
    ai_pre_score: 'ఏఐ స్కోర్',
    rate: 'రేట్ చేయండి',
    consensus_draw: '0.5 కాన్సెన్సస్ డ్రా',
    filter_media_types: 'మీడియా రకాలు ఫిల్టర్ చేయండి',
    apply_filters: 'ఫిల్టర్‌లను వర్తింపజేయండి',
    sort_discovery_feed: 'క్రమబద్ధీకరించు',
    system_notifications: 'సిస్టమ్ నోటిఫికేషన్లు',
    reward_won: 'బహుమతి గెలుచుకున్నారు',
    view_all_rewards: 'అన్ని బహుమతులు చూడండి',
    all_caught_up: 'అన్నీ నవీకరించబడ్డాయి',
    no_notifications_sub: 'కొత్త రివార్డ్ వోచర్ డ్రాలు ఇక్కడ కనిపిస్తాయి.',
    account_suspended: 'ఖాతా తాత్కాలికంగా నిలిపివేయబడింది',
    email_support_team: 'సపోర్ట్ బృందానికి ఇమెయిల్ చేయండి',
    log_out: 'లాగ్ అవుట్',
    rate_content: 'రేటింగ్ ఇవ్వండి',
    verifying_audit: 'ఆడిట్ స్థితి తనిఖీ చేయబడుతోంది...',
    parameters: 'పారామితులు',
    ai_formatting_on: 'ఏఐ స్థితి: ఆన్‌లో ఉంది',
    record_audio_video: 'ఆడియో/వీడియో రికార్డ్ చేయండి',
    type_input_placeholder: 'ఇక్కడ సమీక్షను టైప్ చేయండి లేదా రికార్డింగ్ జోడించండి...',
    processing_ai: 'ఏఐ విశ్లేషిస్తోంది...',
    submit_review: 'సమీక్షను సమర్పించండి',
    report_content: 'నివేదించండి',
    submission_analytics: 'సమర్పణ విశ్లేషణ',
    rating: 'రేటింగ్',
    quality: 'నాణ్యత',
    ai_synthesized_review_output: 'ఏఐ సారాంశం',
    return_to_feed: 'ఫీడ్‌కి తిరిగి వెళ్లండి ►',
    share_audit: 'ఆడిట్ భాగస్వామ్యం చేయండి',
    total_reviewed: 'మొత్తం సమీక్షించిన అంశాలు',
    account_settings: 'ఖాతా సెట్టింగ్‌లు',
    my_reviewed_items: 'నా సమీక్షలు',
    my_rewards: 'నా బహుమతులు',
    edit_profile: 'ప్రొఫైల్ సవరించండి',
    help_support: 'సహాయం & మద్దతు',
    audit_history: 'ఆడిట్ చరిత్ర',
    filter: 'ఫిల్టర్',
    syncing_review_archive: 'సమీక్షల చరిత్ర లోడ్ అవుతోంది...',
    evaluated_on: 'సమీక్షించిన తేదీ',
    sentiment: 'సెంటిమెంట్:',
    reward_unlocked: 'బహుమతి అన్‌లాక్ చేయబడింది',
    view_consensus: 'కాన్సెన్సస్ చూడండి →',
    no_evaluations_found: 'మీ ఖాతాలో ఎలాంటి సమీక్షలు కనుగొనబడలేదు.',
    rate_media_sub: 'మీ సమీక్షల చరిత్రను నిర్మించడానికి కంటెంట్‌ను రేట్ చేయండి.',
    filter_reviews: 'సమీక్షలను ఫిల్టర్ చేయండి',
    reset: 'రీసెట్',
    content_type: 'కంటెంట్ రకం',
    reward_status: 'రివార్డ్ స్థితి',
    all_types: 'అన్ని రకాలు',
    all_reviews: 'అన్ని సమీక్షలు',
    reward_vouchers_unlocked: 'అన్‌లాక్ చేయబడిన రివార్డులు మాత్రమే',
    no_rewards: 'బహుమతులు లేవు',
    unlocked_vouchers: 'అన్‌లాక్ చేయబడిన వోచర్‌లు',
    syncing_reward_ledger: 'రివార్డ్స్ లోడ్ అవుతున్నాయి...',
    won: 'గెలిచినది:',
    sponsor: 'స్పాన్సర్:',
    redeemed: 'వినియోగించబడింది',
    unclaimed: 'క్లెయిమ్ చేయనిది',
    no_won_vouchers: 'మీ ఖాతాలో వోచర్‌లు లేవు.',
    rate_content_sub: 'లక్కీ డ్రా బహుమతులు గెలవడానికి 0.5 కాన్సెన్సస్ మోడ్ సరిపోలండి.',
    reward_voucher: 'రివార్డ్ వోచర్',
    issued_by: 'జారీ చేసినవారు:',
    voucher_redemption_code: 'వోచర్ రిడెంప్షన్ కోడ్',
    present_code_desc: 'మీ రివార్డ్‌ను రీడీమ్ చేయడానికి స్పాన్సర్ వెబ్‌సైట్‌లో ఈ కోడ్‌ను వర్తింపజేయండి.',
    mark_as_redeemed: 'వినియోగించినట్లు గుర్తించండి',
    voucher_already_redeemed: 'వోచర్ ఇప్పటికే వినియోగించబడింది',
    voucher_status: 'వోచర్ స్థితి',
    all_vouchers: 'అన్ని వోచర్‌లు',
    unclaimed_only: 'క్లెయిమ్ చేయనివి మాత్రమే',
    redeemed_only: 'వినియోగించినవి మాత్రమే',
    consensus_rewards: 'కాన్సెన్సస్ & రివార్డులు',
    consensus_tab: '0.5 కాన్సెన్సస్',
    lucky_draw_tab: 'లక్కీ డ్రా రివార్డులు',
    calculating_bins: '0.5 కాన్సెన్సస్ లెక్కిస్తోంది...',
    current_consensus_peak: 'ప్రస్తుత కాన్సెన్సస్ మోడ్ పీక్',
    in_draw_pool: 'డ్రా పూల్‌లో ఉన్నారు',
    crowd_rating_distribution: 'సమూహ రేటింగ్ పంపిణీ (0.0 – 10.0)',
    consensus_peak: 'కాన్సెన్సస్ పీక్',
    your_rating: 'మీ రేటింగ్',
    top_consensus_rankings: 'టాప్ కాన్సెన్సస్ ర్యాంకింగ్‌లు',
    rating_bucket: 'రేటింగ్ బకెట్',
    evaluators: 'సమీక్షకులు',
    votes: 'ఓట్లు',
    winners_draw: 'విజేతలు',
    reward_budget: 'రివార్డ్ బడ్జెట్:',
    status: 'స్థితి:',
    target: 'లక్ష్యం:',
    full_name: 'పూర్తి పేరు',
    phone_number: 'ఫోన్ నంబర్',
    verified: 'ధృవీకరించబడింది',
    email: 'ఇమెయిల్',
    date_of_birth: 'పుట్టిన తేదీ',
    month: 'నెల',
    day: 'రోజు',
    year: 'సంవత్సరం',
    country: 'దేశం',
    state_province: 'రాష్ట్రం',
    city: 'నగరం',
    street_address: 'చిరునామా',
    address_line_2: 'చిరునామా లైన్ 2 (ఐచ్ఛికం)',
    languages_known: 'తెలిసిన భాషలు',
    select_more_language: 'మరిన్ని భాషలను ఎంచుకోండి',
    gender_optional: 'లింగం (ఐచ్ఛికం)',
    male: 'పురుషుడు',
    female: 'స్త్రీ',
    other: 'ఇతర',
    save_profile: 'ప్రొఫైల్ సేవ్ చేయండి',
    saving: 'సేవ్ అవుతోంది...',
    select_languages_modal: 'తెలిసిన భాషలను ఎంచుకోండి',
    changes_not_saved_title: 'మార్పులు సేవ్ చేయబడవు',
    changes_not_saved_sub: 'మీరు మార్పులను విస్మరించి నిష్క్రమించాలనుకుంటున్నారా?',
    discard: 'విస్మరించు',
    keep_editing: 'సవరించడం కొనసాగించండి',
    consumer_auth: 'వినియోగదారు లాగిన్',
    email_or_phone: 'ఇమెయిల్ లేదా ఫోన్ నంబర్',
    generate_otp: 'ఓటీపీ\nపొందండి',
    otp_label: 'ఓటీపీ ధృవీకరణ',
    accept_terms_prefix: 'నేను అంగీకరిస్తున్నాను ',
    terms_link: 'నిబంధనలు మరియు గోప్యతా విధానం',
    login_button: 'లాగిన్ చేయండి',
    or_social_login: 'లేదా సోషల్ లాగిన్',
    new_user_register: 'కొత్త వినియోగదారులా? ఇక్కడ నమోదు చేసుకోండి',
    faq_section_title: 'తరచుగా అడిగే ప్రశ్నలు',
    contact_support_team: 'మద్దతు బృందాన్ని సంప్రదించండి',
    select_category: 'సమస్య వర్గాన్ని ఎంచుకోండి',
    subject: 'విషయం',
    subject_placeholder: 'సమస్య యొక్క సంక్షిప్త వివరణ...',
    detailed_message: 'వివరణాత్మక సందేశం',
    message_placeholder: 'ఏమి జరిగిందో వివరించండి...',
    submit_ticket: 'సపోర్ట్ టిక్కెట్‌ను సమర్పించండి',
    skip: 'దాటవేయి',
    get_started: 'ప్రారంభించండి',
    next: 'తరువాత',
    onboarding_title_1: 'ప్రత్యేక రివార్డులను పొందండి',
    onboarding_desc_1: 'ఉత్తమ సమీక్షకుల సంఘంలో చేరండి మరియు ప్రీమియం ఫీచర్‌లను పొందండి.',
    onboarding_title_2: 'మీ రివార్డ్ పోర్ట్‌ఫోలియో',
    onboarding_desc_2: 'మీ పురోగతిని మరియు సంపాదించిన రివార్డులను ట్రాక్ చేయండి.',
    onboarding_title_3: 'రివార్డుల కోసం రేట్ చేయండి',
    onboarding_desc_3: 'ప్రతి ఖచ్చితమైన రేటింగ్ మిమ్మల్ని కొత్త రివార్డులకు చేరువ చేస్తుంది.',
    onboarding_title_4: 'టాప్ పర్సంటైల్ ర్యాంక్',
    onboarding_desc_4: 'అత్యుత్తమ రివార్డులను పొందడానికి టాప్ 5% ఖచ్చితత్వాన్ని చేరుకోండి.',
    onboarding_title_5: 'మీ ప్రయాణాన్ని ప్రారంభించండి',
    onboarding_desc_5: 'ఖచ్చితమైన సమీక్షలు మీ విజయానికి కీలకం. ప్రారంభించండి.',
    create_consumer_profile: 'ప్రొఫైల్ సృష్టించండి',
    username_handle: 'వినియోగదారు పేరు (@హ్యాండిల్)',
    select_country: 'దేశాన్ని ఎంచుకోండి',
    select_state: 'రాష్ట్రాన్ని ఎంచుకోండి',
    complete_profile_button: 'ప్రొఫైల్ పూర్తి చేయండి ►',
    clear: 'క్లియర్',
    report_media_headline: 'మీడియా కంటెంట్‌ను నివేదించండి',
    report_media_subtext: 'దయచేసి మీ ఆందోళనకు సరిపోయే సరైన కారణాన్ని ఎంచుకోండి.',
    reason_age_inappropriate: 'వయస్సుకి తగనిది',
    reason_unrelated_content: 'సంబంధం లేని కంటెంట్',
    reason_false_ad: 'తప్పుడు ప్రకటన / కంటెంట్',
    reason_other: 'ఇతర',
    submit_report: 'నివేదికను సమర్పించండి',
    cancel: 'రద్దు చేయండి',
    terms_privacy_title: 'నిబంధనలు & గోప్యతా విధానం',
    privacy_policy_tab: 'గోప్యతా విధానం (DPDP 2023)',
    terms_of_service_tab: 'సేవా నిబంధనలు',
    legal_compliance_header: 'చట్టబద్ధమైన నిబంధనలు: భారతదేశ డిజిటల్ వ్యక్తిగత డేటా రక్షణ చట్టం 2023 • ఐటీ చట్టం 2000',
    understand_accept_policies: 'నేను విధానాలను అర్థం చేసుకున్నాను & అంగీకరిస్తున్నాను',
    media_recording_studio: 'మీడియా రికార్డింగ్ స్టూడియో',
    audio_review: 'ఆడియో సమీక్ష',
    video_review: 'వీడియో సమీక్ష',
    video_preview_ready: 'వీడియో ప్రివ్యూ సిద్ధంగా ఉంది',
    camera_viewfinder_active: 'కెమెరా వీక్షణ సక్రియంగా ఉంది',
    audio_preview_ready: 'ఆడియో ప్రివ్యూ సిద్ధంగా ఉంది',
    microphone_active: 'మైక్రోఫోన్ సక్రియంగా ఉంది',
    re_record: 'మళ్లీ రికార్డ్ చేయండి',
    attach_to_review: 'సమీక్షకు జోడించండి ✓',
    TRAILER: 'ట్రైలర్',
    POSTER: 'పోస్టర్',
    SONG: 'పాట',
    PODCAST: 'పాడ్‌కాస్ట్',
    ARTICLE: 'వ్యాసం',
    TEXT: 'టెక్స్ట్',
    AUDIO: 'ఆడియో',
    VIDEO: 'వీడియో',
    Acting: 'నటన',
    Visuals: 'దృశ్యాలు',
    Pacing: 'వేగం',
    Originality: 'సృజనాత్మకత',
    Audio: 'ఆడియో',
    Direction: 'దర్శకత్వం',
    Cinematography: 'ఛాయాగ్రహణం'
  },
  TA: {
    choose_language: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    tab_discover: 'கண்டறிக',
    tab_ratings: 'மதிப்பீடுகள்',
    tab_profile: 'சுயவிவரம்',
    search_placeholder: 'தலைப்புகள் அல்லது படைப்பாளர்களைத் தேடுங்கள்...',
    syncing_stream: 'ஏற்றப்படுகிறது...',
    no_content_matched: 'முடிவுகள் எதுவும் இல்லை',
    no_content_sub: 'உங்கள் தேடலுக்குப் பொருந்தக்கூடிய உள்ளடக்கம் கிடைக்கவில்லை.',
    ai_pre_score: 'ஏஐ மதிப்பெண்',
    rate: 'மதிப்பிடு',
    consensus_draw: '0.5 ஒருமித்த டிரா',
    filter_media_types: 'ஊடக வகைகளை வடிகட்டவும்',
    apply_filters: 'வடிகட்டிகளைப் பயன்படுத்து',
    sort_discovery_feed: 'வரிசைப்படுத்து',
    system_notifications: 'அறிவிப்புகள்',
    reward_won: 'வெற்றி பெற்ற பரிசு',
    view_all_rewards: 'அனைத்து பரிசுகளையும் காண்க',
    all_caught_up: 'அனைத்தும் புதுப்பிக்கப்பட்டது',
    no_notifications_sub: 'புதிய பரிசு வவுச்சர் டிராக்கள் இங்கே தோன்றும்.',
    account_suspended: 'கணக்கு இடைநிறுத்தப்பட்டது',
    email_support_team: 'ஆதரவு குழுவுக்கு மின்னஞ்சல் அனுப்பவும்',
    log_out: 'வெளியேறு',
    rate_content: 'மதிப்பீடு செய்',
    verifying_audit: 'மதிப்பாய்வு நிலை சரிபார்க்கப்படுகிறது...',
    parameters: 'அளவுகோல்கள்',
    ai_formatting_on: 'ஏஐ நிலை: செயலில் உள்ளது',
    record_audio_video: 'ஆடியோ/வீடியோ பதிவு செய்',
    type_input_placeholder: 'இங்கே தட்டச்சு செய்யவும் அல்லது பதிவை இணைக்கவும்...',
    processing_ai: 'ஏஐ செயலாக்குகிறது...',
    submit_review: 'சமர்ப்பிக்கவும்',
    report_content: 'புகாரளி',
    submission_analytics: 'சமர்ப்பிப்பு பகுப்பாய்வு',
    rating: 'மதிப்பீடு',
    quality: 'தரம்',
    ai_synthesized_review_output: 'ஏஐ சுருக்கம்',
    return_to_feed: 'முகப்புக்குத் திரும்பு ►',
    share_audit: 'பகிர்',
    total_reviewed: 'மதிப்பாய்வு செய்யப்பட்டவை',
    account_settings: 'கணக்கு அமைப்புகள்',
    my_reviewed_items: 'என் மதிப்பாய்வுகள்',
    my_rewards: 'என் பரிசுகள்',
    edit_profile: 'சுயவிவரத்தைத் திருத்து',
    help_support: 'உதவி மற்றும் ஆதரவு',
    audit_history: 'மதிப்பாய்வு வரலாறு',
    filter: 'வடிகட்டி',
    syncing_review_archive: 'வரலாறு ஏற்றப்படுகிறது...',
    evaluated_on: 'மதிப்பாய்வு செய்யப்பட்ட நாள்',
    sentiment: 'கருத்து:',
    reward_unlocked: 'பரிசு திறக்கப்பட்டது',
    view_consensus: 'ஒருமித்த கருத்தைப் பார் →',
    no_evaluations_found: 'மதிப்பாய்வுகள் எதுவும் இல்லை.',
    rate_media_sub: 'உங்கள் மதிப்பாய்வு வரலாற்றை உருவாக்க உள்ளடக்கத்தை மதிப்பிடவும்.',
    filter_reviews: 'மதிப்பாய்வுகளை வடிகட்டு',
    reset: 'மீட்டமை',
    content_type: 'உள்ளடக்க வகை',
    reward_status: 'பரிசு நிலை',
    all_types: 'அனைத்து வகைகள்',
    all_reviews: 'அனைத்து மதிப்பாய்வுகள்',
    reward_vouchers_unlocked: 'திறக்கப்பட்ட பரிசுகள் மட்டும்',
    no_rewards: 'பரிசுகள் இல்லை',
    unlocked_vouchers: 'திறக்கப்பட்ட வவுச்சர்கள்',
    syncing_reward_ledger: 'பரிசுகள் ஏற்றப்படுகின்றன...',
    won: 'வென்றது:',
    sponsor: 'ஸ்பான்சர்:',
    redeemed: 'பயன்படுத்தப்பட்டது',
    unclaimed: 'கோரப்படாதது',
    no_won_vouchers: 'வென்ற வவுச்சர்கள் எதுவும் இல்லை.',
    rate_content_sub: 'பரிசுகளை வெல்ல 0.5 ஒருமித்த கருத்தைப் பொருத்துங்கள்.',
    reward_voucher: 'பரிசு வவுச்சர்',
    issued_by: 'வழங்கியவர்:',
    voucher_redemption_code: 'வவுச்சர் மீட்புக் குறியீடு',
    present_code_desc: 'உங்கள் பரிசைப் பெற ஸ்பான்சர் இணையதளத்தில் இந்தக் குறியீட்டைப் பயன்படுத்தவும்.',
    mark_as_redeemed: 'பயன்படுத்தப்பட்டதாகக் குறிக்கவும்',
    voucher_already_redeemed: 'வவுச்சர் ஏற்கனவே பயன்படுத்தப்பட்டது',
    voucher_status: 'வவுச்சர் நிலை',
    all_vouchers: 'அனைத்து வவுச்சர்கள்',
    unclaimed_only: 'கோரப்படாதவை மட்டும்',
    redeemed_only: 'பயன்படுத்தப்பட்டவை மட்டும்',
    consensus_rewards: 'ஒருமித்த கருத்து & பரிசுகள்',
    consensus_tab: '0.5 ஒருமித்த கருத்து',
    lucky_draw_tab: 'லக்கி டிரா பரிசுகள்',
    calculating_bins: '0.5 ஒருமித்த கருத்து கணக்கிடப்படுகிறது...',
    current_consensus_peak: 'தற்போதைய ஒருமித்த உச்சி',
    in_draw_pool: 'டிரா குழுவில் உள்ளீர்கள்',
    crowd_rating_distribution: 'மதிப்பீட்டு விநியோகம் (0.0 – 10.0)',
    consensus_peak: 'ஒருமித்த உச்சி',
    your_rating: 'உங்கள் மதிப்பீடு',
    top_consensus_rankings: 'முதன்மை ஒருமித்த தரவரிசை',
    rating_bucket: 'மதிப்பீட்டுப் பிரிவு',
    evaluators: 'மதிப்பாய்வாளர்கள்',
    votes: 'வாக்குகள்',
    winners_draw: 'வெற்றியாளர்கள்',
    reward_budget: 'பரிசு பட்ஜெட்:',
    status: 'நிலை:',
    target: 'இலக்கு:',
    full_name: 'முழு பெயர்',
    phone_number: 'தொலைபேசி எண்',
    verified: 'சரிபார்க்கப்பட்டது',
    email: 'மின்னஞ்சல்',
    date_of_birth: 'பிறந்த தேதி',
    month: 'மாதம்',
    day: 'நாள்',
    year: 'வருடம்',
    country: 'நாடு',
    state_province: 'மாநிலம்',
    city: 'நகரம்',
    street_address: 'தெரு முகவரி',
    address_line_2: 'முகவரி வரி 2 (விருப்பமானது)',
    languages_known: 'தெரிந்த மொழிகள்',
    select_more_language: 'கூடுதல் மொழியைத் தேர்ந்தெடுக்கவும்',
    gender_optional: 'பாலினம் (விருப்பமானது)',
    male: 'ஆண்',
    female: 'பெண்',
    other: 'மற்றவை',
    save_profile: 'சுயவிவரத்தைச் சேமி',
    saving: 'சேமிக்கப்படுகிறது...',
    select_languages_modal: 'தெரிந்த மொழிகளைத் தேர்ந்தெடுக்கவும்',
    changes_not_saved_title: 'மாற்றங்கள் சேமிக்கப்படாது',
    changes_not_saved_sub: 'மாற்றங்களை நிராகரித்து வெளியேற விரும்புகிறீர்களா?',
    discard: 'நிராகரி',
    keep_editing: 'தொடர்ந்து திருத்து',
    consumer_auth: 'பயனர் உள்நுழைவு',
    email_or_phone: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    generate_otp: 'OTP\nபெறுக',
    otp_label: 'OTP சரிபார்ப்பு',
    accept_terms_prefix: 'நான் ஏற்கிறேன் ',
    terms_link: 'விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கை',
    login_button: 'உள்நுழைக',
    or_social_login: 'அல்லது சமூக உள்நுழைவு',
    new_user_register: 'புதிய பயனரா? இங்கே பதிவு செய்யவும்',
    faq_section_title: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    contact_support_team: 'ஆதரவுக் குழுவைத் தொடர்பு கொள்ளவும்',
    select_category: 'வகை தேர்ந்தெடுக்கவும்',
    subject: 'பொருள்',
    subject_placeholder: 'சுருக்கமான விளக்கம்...',
    detailed_message: 'விரிவான செய்தி',
    message_placeholder: 'விவரங்களை உள்ளிடவும்...',
    submit_ticket: 'டிக்கெட்டைச் சமர்ப்பிக்கவும்',
    skip: 'தவிர்',
    get_started: 'தொடங்கு',
    next: 'அடுத்து',
    onboarding_title_1: 'பிரத்யேக பரிசுகளைப் பெறுங்கள்',
    onboarding_desc_1: 'சிறந்த மதிப்பாய்வாளர்களின் சமூகத்தில் சேர்ந்து பிரீமியம் அம்சங்களை அணுகவும்.',
    onboarding_title_2: 'உங்கள் பரிசுத் தொகுப்பு',
    onboarding_desc_2: 'உங்கள் முன்னேற்றம் மற்றும் வென்ற பரிசுகளைக் கண்காணிக்கவும்.',
    onboarding_title_3: 'பரிசுகளுக்காக மதிப்பிடவும்',
    onboarding_desc_3: 'ஒவ்வொரு துல்லியமான மதிப்பீடும் உங்களை புதிய பரிசுகளுக்கு நெருக்கமாக்குகிறது.',
    onboarding_title_4: 'உயர் சதவீத தரம்',
    onboarding_desc_4: 'சிறந்த திட்டப் பரிசுகளைப் பெற முதல் 5% துல்லியத்தை அடையுங்கள்.',
    onboarding_title_5: 'உங்கள் பயணத்தைத் தொடங்குங்கள்',
    onboarding_desc_5: 'துல்லியமான மதிப்பாய்வுகள் உங்கள் வெற்றிக்கான திறவுகோல்.',
    create_consumer_profile: 'சுயவிவரத்தை உருவாக்கவும்',
    username_handle: 'பயனர் பெயர் (@ஹேண்டில்)',
    select_country: 'நாட்டைத் தேர்ந்தெடுக்கவும்',
    select_state: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    complete_profile_button: 'சுயவிவரத்தை முடிக்கவும் ►',
    clear: 'அழி',
    report_media_headline: 'உள்ளடக்கத்தைப் புகாரளிக்கவும்',
    report_media_subtext: 'தயவுசெய்து உங்கள் கவலைக்குரிய காரணத்தைத் தேர்ந்தெடுக்கவும்.',
    reason_age_inappropriate: 'வயதுக்கு பொருந்தாதது',
    reason_unrelated_content: 'தொடர்பற்ற உள்ளடக்கம்',
    reason_false_ad: 'தவறான விளம்பரம் / உள்ளடக்கம்',
    reason_other: 'மற்றவை',
    submit_report: 'புகாரைச் சமர்ப்பிக்கவும்',
    cancel: 'ரத்து செய்',
    terms_privacy_title: 'விதிமுறைகள் & தனியுரிமைக் கொள்கை',
    privacy_policy_tab: 'தனியுரிமைக் கொள்கை (DPDP 2023)',
    terms_of_service_tab: 'சேவை விதிமுறைகள்',
    legal_compliance_header: 'இணக்கம்: இந்திய டிஜிட்டல் தனிநபர் தரவு பாதுகாப்பு சட்டம் 2023 • ஐடி சட்டம் 2000',
    understand_accept_policies: 'நான் கொள்கைகளைப் புரிந்து கொண்டு ஏற்கிறேன்',
    media_recording_studio: 'மீடியா பதிவு அரங்கம்',
    audio_review: 'ஆடியோ மதிப்பாய்வு',
    video_review: 'வீடியோ மதிப்பாய்வு',
    video_preview_ready: 'வீடியோ முன்னோட்டம் தயார்',
    camera_viewfinder_active: 'கேமரா காட்சி செயலில் உள்ளது',
    audio_preview_ready: 'ஆடியோ முன்னோட்டம் தயார்',
    microphone_active: 'மைக்ரோஃபோன் செயலில் உள்ளது',
    re_record: 'மீண்டும் பதிவு செய்',
    attach_to_review: 'மதிப்பாய்வில் இணைக்கவும் ✓',
    TRAILER: 'டிரெய்லர்',
    POSTER: 'சுவரொட்டி',
    SONG: 'பாடல்',
    PODCAST: 'பாட்காஸ்ட்',
    ARTICLE: 'கட்டுரை',
    TEXT: 'உரை',
    AUDIO: 'ஆடியோ',
    VIDEO: 'வீடியோ',
    Acting: 'நடிப்பு',
    Visuals: 'காட்சிகள்',
    Pacing: 'வேகம்',
    Originality: 'தனித்துவம்',
    Audio: 'ஒலி',
    Direction: 'இயக்கம்',
    Cinematography: 'ஒளிப்பதிவு'
  },
  ES: {
    choose_language: 'Elige tu idioma',
    tab_discover: 'DESCUBRIR',
    tab_ratings: 'CALIFICACIONES',
    tab_profile: 'PERFIL',
    search_placeholder: 'Buscar títulos, formatos o creadores...',
    syncing_stream: 'SINCRONIZANDO CONTENIDO...',
    no_content_matched: 'NO SE ENCONTRÓ CONTENIDO',
    no_content_sub: 'No se encontraron elementos que coincidan con la búsqueda.',
    ai_pre_score: 'PRE-PUNTAJE IA',
    rate: 'CALIFICAR',
    consensus_draw: 'SORTEO DE CONSENSO 0.5',
    filter_media_types: 'FILTRAR POR FORMATO',
    apply_filters: 'APLICAR FILTROS',
    sort_discovery_feed: 'ORDENAR FEED',
    system_notifications: 'NOTIFICACIONES DEL SISTEMA',
    reward_won: 'RECOMPENSA GANADA',
    view_all_rewards: 'VER TODAS LAS RECOMPENSAS',
    all_caught_up: 'Todo al día',
    no_notifications_sub: 'Los nuevos sorteos de recompensas aparecerán aquí.',
    account_suspended: 'CUENTA SUSPENDIDA',
    email_support_team: 'CORREO AL EQUIPO DE SOPORTE',
    log_out: 'CERRAR SESIÓN',
    rate_content: 'CALIFICAR CONTENIDO',
    verifying_audit: 'VERIFICANDO ESTADO DE AUDITORÍA...',
    parameters: 'PARÁMETROS',
    ai_formatting_on: 'ESTADO DE FORMATO IA: ACTIVO',
    record_audio_video: 'GRABAR AUDIO/VIDEO',
    type_input_placeholder: 'Escribe tu reseña o adjunta grabación...',
    processing_ai: 'PROCESANDO CON GEMINI IA...',
    submit_review: 'ENVIAR RESEÑA',
    report_content: 'REPORTAR CONTENIDO',
    submission_analytics: 'ANÁLISIS DE ENVÍO',
    rating: 'CALIFICACIÓN',
    quality: 'CALIDAD',
    ai_synthesized_review_output: 'RESUMEN SINTETIZADO POR IA',
    return_to_feed: 'VOLVER AL FEED ►',
    share_audit: 'COMPARTIR AUDITORÍA',
    total_reviewed: 'TOTAL DE ELEMENTOS EVALUADOS',
    account_settings: 'AJUSTES DE LA CUENTA',
    my_reviewed_items: 'Mis Evaluaciones',
    my_rewards: 'Mis Recompensas',
    edit_profile: 'Editar Perfil',
    help_support: 'Ayuda y Soporte',
    audit_history: 'HISTORIAL DE AUDITORÍA',
    filter: 'Filtrar',
    syncing_review_archive: 'SINCRONIZANDO HISTORIAL...',
    evaluated_on: 'EVALUADO EL',
    sentiment: 'SENTIMIENTO:',
    reward_unlocked: 'RECOMPENSA DESBLOQUEADA',
    view_consensus: 'Ver Consenso →',
    no_evaluations_found: 'No se encontraron evaluaciones en tu archivo.',
    rate_media_sub: 'Califica contenido en el feed para construir tu historial.',
    filter_reviews: 'FILTRAR RESEÑAS',
    reset: 'Restablecer',
    content_type: 'TIPO DE CONTENIDO',
    reward_status: 'ESTADO DE RECOMPENSA',
    all_types: 'Todos los Tipos',
    all_reviews: 'Todas las Reseñas',
    reward_vouchers_unlocked: 'Solo Recompensas Desbloqueadas',
    no_rewards: 'Sin Recompensas',
    unlocked_vouchers: 'VALES DESBLOQUEADOS',
    syncing_reward_ledger: 'SINCRONIZANDO RECOMPENSAS...',
    won: 'GANADO:',
    sponsor: 'PATROCINADOR:',
    redeemed: 'CANJEADO',
    unclaimed: 'NO RECLAMADO',
    no_won_vouchers: 'No tienes vales ganados en tu registro.',
    rate_content_sub: 'Califica contenido y acierta el consenso de 0.5 para ganar recompensas.',
    reward_voucher: 'VALE DE RECOMPENSA',
    issued_by: 'Emitido por',
    voucher_redemption_code: 'CÓDIGO DE CANJE DE VALE',
    present_code_desc: 'Presenta o aplica este código en el sitio web del patrocinador para canjear.',
    mark_as_redeemed: 'MARCAR COMO CANJEADO',
    voucher_already_redeemed: 'VALE YA CANJEADO',
    voucher_status: 'ESTADO DEL VALE',
    all_vouchers: 'Todos los Vales',
    unclaimed_only: 'Solo No Reclamados',
    redeemed_only: 'Solo Canjeados',
    consensus_rewards: 'CONSENSO Y RECOMPENSAS',
    consensus_tab: 'CONSENSO 0.5',
    lucky_draw_tab: 'SORTEOS DE RECOMPENSAS',
    calculating_bins: 'CALCULANDO RANGOS DE CONSENSO 0.5...',
    current_consensus_peak: 'PICO DE CONSENSO ACTUAL',
    in_draw_pool: 'EN EL GRUPO DEL SORTEO',
    crowd_rating_distribution: 'DISTRIBUCIÓN DE CALIFICACIONES (0.0 – 10.0)',
    consensus_peak: 'Pico de Consenso',
    your_rating: 'Tu Calificación',
    top_consensus_rankings: 'RANGOS DE CONSENSO PRINCIPALES',
    rating_bucket: 'Rango de Calificación',
    evaluators: 'Evaluadores',
    votes: 'votos',
    winners_draw: 'GANADORES',
    reward_budget: 'PRESUPUESTO:',
    status: 'ESTADO:',
    target: 'OBJETIVO:',
    full_name: 'NOMBRE COMPLETO',
    phone_number: 'NÚMERO DE TELÉFONO',
    verified: 'VERIFICADO',
    email: 'CORREO ELECTRÓNICO',
    date_of_birth: 'FECHA DE NACIMIENTO',
    month: 'MES',
    day: 'DÍA',
    year: 'AÑO',
    country: 'PAÍS',
    state_province: 'ESTADO / PROVINCIA',
    city: 'CIUDAD',
    street_address: 'DIRECCIÓN',
    address_line_2: 'DIRECCIÓN LÍNEA 2 (OPCIONAL)',
    languages_known: 'IDIOMAS CONOCIDOS',
    select_more_language: 'Seleccionar Más Idiomas',
    gender_optional: 'GÉNERO (OPCIONAL)',
    male: 'MASCULINO',
    female: 'FEMENINO',
    other: 'OTRO',
    save_profile: 'GUARDAR PERFIL',
    saving: 'GUARDANDO...',
    select_languages_modal: 'SELECCIONAR IDIOMAS',
    changes_not_saved_title: 'LOS CAMBIOS NO SE GUARDARÁN',
    changes_not_saved_sub: '¿DESEAS DESCARTAR LOS CAMBIOS Y SALIR?',
    discard: 'DESCARTAR',
    keep_editing: 'SEGUIR EDITANDO',
    consumer_auth: 'AUTENTICACIÓN DE USUARIO',
    email_or_phone: 'CORREO O NÚMERO DE TELÉFONO',
    generate_otp: 'GENERAR\nOTP',
    otp_label: 'VERIFICACIÓN OTP',
    accept_terms_prefix: 'Acepto los ',
    terms_link: 'Términos de Servicio y Política de Privacidad',
    login_button: 'INICIAR SESIÓN',
    or_social_login: 'O INICIO DE SESIÓN SOCIAL',
    new_user_register: '¿NUEVO USUARIO? REGÍSTRATE AQUÍ',
    faq_section_title: 'PREGUNTAS FRECUENTES',
    contact_support_team: 'CONTACTAR AL EQUIPO DE SOPORTE',
    select_category: 'SELECCIONAR CATEGORÍA',
    subject: 'ASUNTO',
    subject_placeholder: 'Breve descripción del problema...',
    detailed_message: 'MENSAJE DETALLADO',
    message_placeholder: 'Describe lo que ocurrió...',
    submit_ticket: 'ENVIAR TICKET DE SOPORTE',
    skip: 'OMITIR',
    get_started: 'EMPEZAR',
    next: 'SIGUIENTE',
    onboarding_title_1: 'Desbloquea Recompensas de Élite',
    onboarding_desc_1: 'Únete a una comunidad de evaluadores y obtén acceso exclusivo a recursos de calidad.',
    onboarding_title_2: 'Tu Portafolio de Recompensas',
    onboarding_desc_2: 'Haz seguimiento de tus logros y ganancias acumuladas.',
    onboarding_title_3: 'Califica por Recompensas',
    onboarding_desc_3: 'Cada evaluación precisa te acerca a nuevos niveles de recompensas patrocinadas.',
    onboarding_title_4: 'Rango de Percentil de Élite',
    onboarding_desc_4: 'Alcanza el 5% superior de precisión para desbloquear los premios más prestigiosos.',
    onboarding_title_5: 'Comienza tu Viaje',
    onboarding_desc_5: 'Las evaluaciones precisas son la clave para construir tu biblioteca.',
    create_consumer_profile: 'CREAR PERFIL DE USUARIO',
    username_handle: 'NOMBRE DE USUARIO (@USUARIO)',
    select_country: 'Seleccionar País',
    select_state: 'Seleccionar Estado',
    complete_profile_button: 'COMPLETAR PERFIL ►',
    clear: 'BORRAR',
    report_media_headline: 'Reportar Contenido',
    report_media_subtext: 'Selecciona el motivo que mejor describa tu inquietud respecto a este contenido.',
    reason_age_inappropriate: 'EDAD INAPROPIADA',
    reason_unrelated_content: 'CONTENIDO NO RELACIONADO',
    reason_false_ad: 'PUBLICIDAD ENGAÑOSA / CONTENIDO FALSO',
    reason_other: 'OTRO',
    submit_report: 'ENVIAR REPORTE',
    cancel: 'CANCELAR',
    terms_privacy_title: 'TÉRMINOS Y POLÍTICA DE PRIVACIDAD',
    privacy_policy_tab: 'POLÍTICA DE PRIVACIDAD (DPDP 2023)',
    terms_of_service_tab: 'TÉRMINOS DE SERVICIO',
    legal_compliance_header: 'CUMPLIMIENTO: LEY DE PROTECCIÓN DE DATOS PERSONALES DIGITALES 2023 • LEY IT 2000',
    understand_accept_policies: 'ENTIENDO Y ACEPTO LAS POLÍTICAS',
    media_recording_studio: 'ESTUDIO DE GRABACIÓN',
    audio_review: 'RESEÑA DE AUDIO',
    video_review: 'RESEÑA DE VIDEO',
    video_preview_ready: 'VISTA PREVIA DE VIDEO LISTA',
    camera_viewfinder_active: 'VISOR DE CÁMARA ACTIVO',
    audio_preview_ready: 'VISTA PREVIA DE AUDIO LISTA',
    microphone_active: 'MICRÓFONO ACTIVO',
    re_record: 'VOLVER A GRABAR',
    attach_to_review: 'ADJUNTAR A LA RESEÑA ✓',
    TRAILER: 'TRÁILER',
    POSTER: 'PÓSTER',
    SONG: 'CANCIÓN',
    PODCAST: 'PÓDCAST',
    ARTICLE: 'ARTÍCULO',
    TEXT: 'TEXTO',
    AUDIO: 'AUDIO',
    VIDEO: 'VIDEO',
    Acting: 'Actuación',
    Visuals: 'Efectos Visuales',
    Pacing: 'Ritmo',
    Originality: 'Originalidad',
    Audio: 'Sonido',
    Direction: 'Dirección',
    Cinematography: 'Cinematografía'
  },
  FR: {
    choose_language: 'Choisissez votre langue',
    tab_discover: 'DÉCOUVRIR',
    tab_ratings: 'ÉVALUATIONS',
    tab_profile: 'PROFIL',
    search_placeholder: 'Rechercher des titres, formats ou créateurs...',
    syncing_stream: 'SYNCHRONISATION DU FLUX...',
    no_content_matched: 'AUCUN CONTENU TROUVÉ',
    no_content_sub: 'Aucun contenu ne correspond à votre recherche.',
    ai_pre_score: 'PRÉ-SCORE IA',
    rate: 'ÉVALUER',
    consensus_draw: 'TIRAGE AU SORT CONSENSUS 0.5',
    filter_media_types: 'FILTRER LES TYPES DE MÉDIA',
    apply_filters: 'APPLIQUER LES FILTRES',
    sort_discovery_feed: 'TRIER LE FLUX',
    system_notifications: 'NOTIFICATIONS DU SYSTÈME',
    reward_won: 'RÉCOMPENSE GAGNÉE',
    view_all_rewards: 'VOIR TOUTES LES RÉCOMPENSES',
    all_caught_up: 'Tout est à jour',
    no_notifications_sub: 'Les nouveaux tirages au sort de récompenses apparaîtront ici.',
    account_suspended: 'COMPTE SUSPENDU',
    email_support_team: "ENVOYER UN E-MAIL À L'ÉQUIPE D'ASSISTANCE",
    log_out: 'SE DÉCONNECTER',
    rate_content: 'ÉVALUER LE CONTENU',
    verifying_audit: 'VÉRIFICATION DU STATUT D\'AUDIT...',
    parameters: 'PARAMÈTRES',
    ai_formatting_on: 'FORMATAGE IA: ACTIVÉ',
    record_audio_video: 'ENREGISTRER AUDIO/VIDÉO',
    type_input_placeholder: 'Rédigez votre avis ou joignez un enregistrement...',
    processing_ai: 'TRAITEMENT PAR GEMINI IA...',
    submit_review: 'SOUMETTRE L\'AVIS',
    report_content: 'SIGNALER LE CONTENU',
    submission_analytics: 'ANALYSE DE LA SOUMISSION',
    rating: 'NOTE',
    quality: 'QUALITÉ',
    ai_synthesized_review_output: 'RÉSUMÉ SYNTHÉTISÉ PAR IA',
    return_to_feed: 'RETOUR AU FLUX ►',
    share_audit: 'PARTAGER L\'AUDIT',
    total_reviewed: 'TOTAL DES ÉLÉMENTS ÉVALUÉS',
    account_settings: 'PARAMÈTRES DU COMPTE',
    my_reviewed_items: 'Mes Évaluations',
    my_rewards: 'Mes Récompenses',
    edit_profile: 'Modifier le Profil',
    help_support: 'Aide & Support',
    audit_history: 'HISTORIQUE D\'AUDIT',
    filter: 'Filtrer',
    syncing_review_archive: 'SYNCHRONISATION DES AVIS...',
    evaluated_on: 'ÉVALUÉ LE',
    sentiment: 'SENTIMENT :',
    reward_unlocked: 'RÉCOMPENSE DÉBLOQUÉE',
    view_consensus: 'Voir le Consensus →',
    no_evaluations_found: 'Aucun avis trouvé dans votre historique.',
    rate_media_sub: 'Évaluez du contenu pour enrichir votre historique.',
    filter_reviews: 'FILTRER LES AVIS',
    reset: 'Réinitialiser',
    content_type: 'TYPE DE CONTENU',
    reward_status: 'STATUT DE RÉCOMPENSE',
    all_types: 'Tous les Types',
    all_reviews: 'Tous les Avis',
    reward_vouchers_unlocked: 'Récompenses Débloquées Uniquement',
    no_rewards: 'Aucune Récompense',
    unlocked_vouchers: 'BONS DÉBLOQUÉS',
    syncing_reward_ledger: 'SYNCHRONISATION DES RÉCOMPENSES...',
    won: 'GAGNÉ :',
    sponsor: 'SPONSOR :',
    redeemed: 'UTILISÉ',
    unclaimed: 'NON RÉCLAMÉ',
    no_won_vouchers: 'Aucun bon gagné dans votre historique.',
    rate_content_sub: 'Évaluez du contenu pour correspondre au consensus 0.5 et gagner des prix.',
    reward_voucher: 'BON DE RÉCOMPENSE',
    issued_by: 'Émis par',
    voucher_redemption_code: 'CODE D\'UTILISATION DU BON',
    present_code_desc: 'Présentez ou appliquez ce code sur le site du sponsor pour utiliser votre bon.',
    mark_as_redeemed: 'MARQUER COMME UTILISÉ',
    voucher_already_redeemed: 'BON DÉJÀ UTILISÉ',
    voucher_status: 'STATUT DU BON',
    all_vouchers: 'Tous les Bons',
    unclaimed_only: 'Non Réclamés Uniquement',
    redeemed_only: 'Utilisés Uniquement',
    consensus_rewards: 'CONSENSUS ET RÉCOMPENSES',
    consensus_tab: 'CONSENSUS 0.5',
    lucky_draw_tab: 'TIRAGES AU SORT',
    calculating_bins: 'CALCUL DES BINS DE CONSENSUS 0.5...',
    current_consensus_peak: 'PIC DE CONSENSUS ACTUEL',
    in_draw_pool: 'DANS LE GROUPE DU TIRAGE',
    crowd_rating_distribution: 'DISTRIBUTION DES NOTES (0.0 – 10.0)',
    consensus_peak: 'Pic de Consensus',
    your_rating: 'Votre Note',
    top_consensus_rankings: 'CLASSEMENT DU CONSENSUS',
    rating_bucket: 'Catégorie de Note',
    evaluators: 'Évaluateurs',
    votes: 'votes',
    winners_draw: 'GAGNANTS',
    reward_budget: 'BUDGET TOTAL :',
    status: 'STATUT :',
    target: 'CIBLE :',
    full_name: 'NOM COMPLET',
    phone_number: 'NUMÉRO DE TÉLÉPHONE',
    verified: 'VÉRIFIÉ',
    email: 'E-MAIL',
    date_of_birth: 'DATE DE NAISSANCE',
    month: 'MOIS',
    day: 'JOUR',
    year: 'ANNÉE',
    country: 'PAYS',
    state_province: 'ÉTAT / PROVINCE',
    city: 'VILLE',
    street_address: 'ADRESSE',
    address_line_2: 'COMPLÉMENT D\'ADRESSE (FACULTATIF)',
    languages_known: 'LANGUES CONNUES',
    select_more_language: 'Sélectionner d\'autres langues',
    gender_optional: 'GENRE (FACULTATIF)',
    male: 'HOMME',
    female: 'FEMME',
    other: 'AUTRE',
    save_profile: 'ENREGISTRER LE PROFIL',
    saving: 'ENREGISTREMENT...',
    select_languages_modal: 'SÉLECTIONNER LES LANGUES',
    changes_not_saved_title: 'LES MODIFICATIONS NE SERONT PAS ENREGISTRÉES',
    changes_not_saved_sub: 'VOULEZ-VOUS ABANDONNER LES MODIFICATIONS ET QUITTER ?',
    discard: 'ABANDONNER',
    keep_editing: 'CONTINUER À MODIFIER',
    consumer_auth: 'AUTHENTIFICATION UTILISATEUR',
    email_or_phone: 'E-MAIL OU NUMÉRO DE TÉLÉPHONE',
    generate_otp: 'GÉNÉRER\nL\'OTP',
    otp_label: 'VÉRIFICATION OTP',
    accept_terms_prefix: 'J\'accepte les ',
    terms_link: 'Conditions d\'utilisation et Politique de Confidentialité',
    login_button: 'SE CONNECTER',
    or_social_login: 'OU CONNEXION SOCIALE',
    new_user_register: 'NOUVEL UTILISATEUR ? INSCRIVEZ-VOUS ICI',
    faq_section_title: 'FOIRE AUX QUESTIONS',
    contact_support_team: 'CONTACTER L\'ÉQUIPE D\'ASSISTANCE',
    select_category: 'SÉLECTIONNER UNE CATÉGORIE',
    subject: 'SUJET',
    subject_placeholder: 'Brève description du problème...',
    detailed_message: 'MESSAGE DÉTAILLÉ',
    message_placeholder: 'Décrivez ce qui s\'est passé...',
    submit_ticket: 'SOUMETTRE LE TICKET',
    skip: 'PASSER',
    get_started: 'COMMENCER',
    next: 'SUIVANT',
    onboarding_title_1: 'Débloquez des Récompenses d\'Élite',
    onboarding_desc_1: 'Rejoignez une communauté d\'évaluateurs et accédez à des contenus exclusifs.',
    onboarding_title_2: 'Votre Portefeuille de Récompenses',
    onboarding_desc_2: 'Suivez vos progrès et vos gains archivés.',
    onboarding_title_3: 'Évaluez pour Gagner',
    onboarding_desc_3: 'Chaque évaluation précise vous rapproche de nouvelles récompenses sponsorisées.',
    onboarding_title_4: 'Rang de Percentile d\'Élite',
    onboarding_desc_4: 'Atteignez le top 5% de précision pour débloquer les récompenses les plus prestigieuses.',
    onboarding_title_5: 'Commencez Votre Voyage',
    onboarding_desc_5: 'Des avis précis sont la clé pour bâtir votre bibliothèque d\'actifs.',
    create_consumer_profile: 'CRÉER UN PROFIL UTILISATEUR',
    username_handle: 'NOM D\'UTILISATEUR (@IDENTIFIANT)',
    select_country: 'Sélectionner le Pays',
    select_state: 'Sélectionner la Région',
    complete_profile_button: 'COMPLÉTER LE PROFIL ►',
    clear: 'EFFACER',
    report_media_headline: 'Signaler un Contenu',
    report_media_subtext: 'Veuillez sélectionner le motif décrivant le mieux votre problème.',
    reason_age_inappropriate: 'ÂGE INAPPROPRIÉ',
    reason_unrelated_content: 'CONTENU SANS RAPPORT',
    reason_false_ad: 'PUBLICITÉ MENSONGÈRE / CONTENU TROMPEUR',
    reason_other: 'AUTRE',
    submit_report: 'SOUMETTRE LE SIGNALEMENT',
    cancel: 'ANNULER',
    terms_privacy_title: 'CONDITIONS ET CONFIDENTIALITÉ',
    privacy_policy_tab: 'POLITIQUE DE CONFIDENTIALITÉ (DPDP 2023)',
    terms_of_service_tab: 'CONDITIONS D\'UTILISATION',
    legal_compliance_header: 'CONFORMITÉ : LOI SUR LA PROTECTION DES DONNÉES 2023 • LOI IT 2000',
    understand_accept_policies: 'JE COMPRENDS ET J\'ACCEPTE LES POLITIQUES',
    media_recording_studio: 'STUDIO D\'ENREGISTREMENT',
    audio_review: 'AVIS AUDIO',
    video_review: 'AVIS VIDÉO',
    video_preview_ready: 'APERÇU VIDÉO PRÊT',
    camera_viewfinder_active: 'VISEUR CAMÉRA ACTIF',
    audio_preview_ready: 'APERÇU AUDIO PRÊT',
    microphone_active: 'MICROPHONE ACTIF',
    re_record: 'RÉENREGISTRER',
    attach_to_review: 'JOINDRE À L\'AVIS ✓',
    TRAILER: 'BANDE-ANNONCE',
    POSTER: 'AFFICHE',
    SONG: 'CHANSON',
    PODCAST: 'PODCAST',
    ARTICLE: 'ARTICLE',
    TEXT: 'TEXTE',
    AUDIO: 'AUDIO',
    VIDEO: 'VIDÉO',
    Acting: 'Jeu d\'acteur',
    Visuals: 'Visuels',
    Pacing: 'Rythme',
    Originality: 'Originalité',
    Audio: 'Son',
    Direction: 'Mise en scène',
    Cinematography: 'Cinématographie'
  }
};

const LanguageContext = createContext({
  language: 'EN',
  setLanguage: () => {},
  t: (key) => key
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('EN');

  useEffect(() => {
    const loadStoredLanguage = async () => {
      try {
        const stored = await AsyncStorage.getItem(STORAGE_KEY);
        if (stored && TRANSLATIONS[stored]) {
          setLanguageState(stored);
        }
      } catch {
        // Fallback to EN
      }
    };
    loadStoredLanguage();
  }, []);

  const setLanguage = async (code) => {
    const upper = String(code || 'EN').toUpperCase();
    if (TRANSLATIONS[upper]) {
      setLanguageState(upper);
      try {
        await AsyncStorage.setItem(STORAGE_KEY, upper);
        const token = await mobileApi.getToken();
        if (token) {
          mobileApi.patch('/users/me', { languagePreferred: upper }).catch(() => {});
        }
      } catch {
        // Ignored
      }
    }
  };

  const t = (key) => {
    if (!key) return '';
    const cleanKey = String(key).trim();
    return (
      TRANSLATIONS[language]?.[cleanKey] ||
      TRANSLATIONS['EN']?.[cleanKey] ||
      cleanKey
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);